// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Q06iwvJyER45X1A18-vg-8-QdXEwSjM',
    appId: '1:1047553211533:web:443e39b2b3ede53a8f76c4',
    messagingSenderId: '1047553211533',
    projectId: 'shoppr-b6a4a',
    authDomain: 'shoppr-b6a4a.firebaseapp.com',
    storageBucket: 'shoppr-b6a4a.firebasestorage.app',
    measurementId: 'G-M4GDJ0L95J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoi7p2FpBazwQ-4L2bs2Hd3QRYtS5Czuk',
    appId: '1:1047553211533:android:b5e46d799bbd32988f76c4',
    messagingSenderId: '1047553211533',
    projectId: 'shoppr-b6a4a',
    storageBucket: 'shoppr-b6a4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvvQVmOFhvA4QMG4vvyEpeEhMhprDrnKc',
    appId: '1:1047553211533:ios:f0e951defba95e458f76c4',
    messagingSenderId: '1047553211533',
    projectId: 'shoppr-b6a4a',
    storageBucket: 'shoppr-b6a4a.firebasestorage.app',
    iosBundleId: 'com.example.shoppr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvvQVmOFhvA4QMG4vvyEpeEhMhprDrnKc',
    appId: '1:1047553211533:ios:f0e951defba95e458f76c4',
    messagingSenderId: '1047553211533',
    projectId: 'shoppr-b6a4a',
    storageBucket: 'shoppr-b6a4a.firebasestorage.app',
    iosBundleId: 'com.example.shoppr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Q06iwvJyER45X1A18-vg-8-QdXEwSjM',
    appId: '1:1047553211533:web:07bc43f519dda7718f76c4',
    messagingSenderId: '1047553211533',
    projectId: 'shoppr-b6a4a',
    authDomain: 'shoppr-b6a4a.firebaseapp.com',
    storageBucket: 'shoppr-b6a4a.firebasestorage.app',
    measurementId: 'G-HEGSKVCY9E',
  );
}
